name: Log latest release

on:
  push:
    branches:
      - main

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install @octokit/graphql package
        run: npm install @octokit/graphql

      - name: Log latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          query=$(cat <<EOF
            query PostsBySpaceId {
              posts(where: { space: { id_eq: "10802" }, hidden_not_eq: true }, orderBy: { field: ID, direction: DESC }) {
                slug
              }
            }
          EOF
          )
          echo "query=$query"
          result=$(npx @octokit/graphql -q "$query" -H "authorization: Bearer $GITHUB_TOKEN")
          echo "latest release: $result"
