name: Log latest release
on:
  push:
    branches:
      - main

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query PostsBySpaceId {
            posts(where: { space: { id_eq: "10802" }, hidden_not_eq: true }, orderBy: { field: ID, direction: DESC }) {
            slug
              }
             }
          variables: |
           owner: ${{ github.event.repository.owner.name }}
           repo: ${{ github.event.repository.name }}
          mediaType: |
            previews:
            - merge-info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
