name: Log posts by space ID

on:
  push:
    branches:
      - main

jobs:
  logPostsBySpaceId:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cURL
        run: sudo apt-get install curl -y

      - name: Execute GraphQL query
        id: execute_query
        run: |
          query='{"query":"query PostsBySpaceId { posts(where: {space: {id_eq: \"10802\"}, AND: {hidden_not_eq: true}}, orderBy: id_DESC) {slug}}"}'
          response=$(curl -X POST -H "Content-Type: application/json" -d "$query" https://squid.subsquid.io/subsocial/graphql)
          echo "::set-output name=response::$response"

      - name: Display query result
        run: echo "Query result: ${{ steps.execute_query.outputs.response }}"
