name: Graphql
on:
  push:
    branches:
      - main

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
  - uses: octokit/graphql-action@v2.x
    with:
      query: |
        query  pullRequest(
          $repo:String!
          $owner:String!) {
          repository(name:$repo, owner:$owner) { 
            pullRequests(last:1) {
              nodes {
                number
                mergeStateStatus
              }
            }
          }
        }
      owner: ${{ github.event.repository.owner.name }}
      repo: ${{ github.event.repository.name }}
      mediaType: |
        previews:
        - merge-info
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run generate
      - run: ls .output/public/index.html
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy app build to S3 bucket
        run: aws s3 sync .output/public/  s3://astarwebtest --delete
