name: CMS Deploy to EC2
'on':
  push:
    branches:
      - ecosystem-page
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/astarwebsite_v2/backend
            npm install pm2@latest -g
            npm install
            NODE_ENV=production npm run build
        
